-- SQL Schema for PolytechnicKarle
-- Copy and run these queries in your Supabase SQL Editor (Dashboard > SQL Editor > New query)

-- ==========================================
-- 1. DATABASE TABLES
-- ==========================================

-- Create 'college_profiles' table
CREATE TABLE IF NOT EXISTS public.college_profiles (
    college_name TEXT PRIMARY KEY,
    location TEXT,
    established INTEGER,
    fees TEXT,
    image_url TEXT,
    description TEXT,
    facilities TEXT[] DEFAULT '{}'::TEXT[],
    seat_matrix_regular JSONB DEFAULT '{}'::JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create 'colleges' table (for cutoff data)
CREATE TABLE IF NOT EXISTS public.colleges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    college_name TEXT NOT NULL,
    branch TEXT NOT NULL,
    category TEXT NOT NULL,
    opening_rank INTEGER,
    closing_rank INTEGER NOT NULL,
    domicile TEXT DEFAULT 'Bihar',
    exam_type TEXT DEFAULT 'DCECE',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.college_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.colleges ENABLE ROW LEVEL SECURITY;

-- Policies for college_profiles
CREATE POLICY "Allow public select on college_profiles" 
ON public.college_profiles FOR SELECT USING (true);

CREATE POLICY "Allow public insert on college_profiles" 
ON public.college_profiles FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public update on college_profiles" 
ON public.college_profiles FOR UPDATE USING (true);

CREATE POLICY "Allow public delete on college_profiles" 
ON public.college_profiles FOR DELETE USING (true);

-- Policies for colleges
CREATE POLICY "Allow public select on colleges" 
ON public.colleges FOR SELECT USING (true);

CREATE POLICY "Allow public insert on colleges" 
ON public.colleges FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public update on colleges" 
ON public.colleges FOR UPDATE USING (true);

CREATE POLICY "Allow public delete on colleges" 
ON public.colleges FOR DELETE USING (true);


-- ==========================================
-- 2. STORAGE BUCKET (For College Photo Uploads)
-- ==========================================

-- Create public bucket 'college-photos'
INSERT INTO storage.buckets (id, name, public)
VALUES ('college-photos', 'college-photos', true)
ON CONFLICT (id) DO NOTHING;

-- Policy to allow public to view files
CREATE POLICY "Allow public select on college-photos"
ON storage.objects FOR SELECT
USING (bucket_id = 'college-photos');

-- Policy to allow public to upload files
CREATE POLICY "Allow public insert on college-photos"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'college-photos');


-- ==========================================
-- 3. STUDENT LEADS TABLE (For Growth & Alerts)
-- ==========================================

-- Create 'student_leads' table
CREATE TABLE IF NOT EXISTS public.student_leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ur_rank INTEGER NOT NULL,
    category_rank INTEGER,
    category TEXT,
    gender TEXT,
    domicile TEXT,
    home_district TEXT,
    whatsapp_number TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.student_leads ENABLE ROW LEVEL SECURITY;

-- Policies for student_leads
CREATE POLICY "Allow public insert on student_leads" 
ON public.student_leads FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow authenticated read on student_leads" 
ON public.student_leads FOR SELECT TO authenticated USING (true);


-- ==========================================
-- 4. CONSULTATIONS TABLE (For Booking Free Guidance)
-- ==========================================

-- Create 'consultations' table
CREATE TABLE IF NOT EXISTS public.consultations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name TEXT NOT NULL,
    whatsapp_number TEXT NOT NULL,
    ur_rank INTEGER NOT NULL,
    category TEXT NOT NULL,
    category_rank INTEGER,
    preferred_branch TEXT,
    contact_preference TEXT DEFAULT 'WhatsApp',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.consultations ENABLE ROW LEVEL SECURITY;

-- Policies for consultations
CREATE POLICY "Allow public insert on consultations" 
ON public.consultations FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow authenticated read on consultations" 
ON public.consultations FOR SELECT TO authenticated USING (true);


-- ==========================================
-- 5. PAYMENTS TABLE (For ₹99 Counselling Guide Payments)
-- ==========================================

-- Create 'payments' table
CREATE TABLE IF NOT EXISTS public.payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name TEXT NOT NULL,
    roll_number TEXT,
    whatsapp_number TEXT,
    amount NUMERIC DEFAULT 99.00,
    payment_mode TEXT DEFAULT 'UPI',
    transaction_id TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

-- Policies for payments
CREATE POLICY "Allow public insert on payments" 
ON public.payments FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public select on payments" 
ON public.payments FOR SELECT USING (true);


-- ==========================================
-- 6. LIVE SEAT MATRIX TABLE
-- ==========================================

-- Create 'live_seat_matrix' table
CREATE TABLE IF NOT EXISTS public.live_seat_matrix (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    college_name TEXT NOT NULL,
    branch TEXT NOT NULL,
    total_seats INTEGER NOT NULL,
    filled_seats INTEGER DEFAULT 0 NOT NULL,
    vacant_seats INTEGER DEFAULT 0 NOT NULL,
    ur INTEGER DEFAULT 0 NOT NULL,
    bc INTEGER DEFAULT 0 NOT NULL,
    ebc INTEGER DEFAULT 0 NOT NULL,
    sc INTEGER DEFAULT 0 NOT NULL,
    st INTEGER DEFAULT 0 NOT NULL,
    ews INTEGER DEFAULT 0 NOT NULL,
    rcg INTEGER DEFAULT 0 NOT NULL,
    dq INTEGER DEFAULT 0 NOT NULL,
    smq INTEGER DEFAULT 0 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.live_seat_matrix ENABLE ROW LEVEL SECURITY;

-- Policies for live_seat_matrix
CREATE POLICY "Allow public select on live_seat_matrix" 
ON public.live_seat_matrix FOR SELECT USING (true);

CREATE POLICY "Allow public insert on live_seat_matrix" 
ON public.live_seat_matrix FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public update on live_seat_matrix" 
ON public.live_seat_matrix FOR UPDATE USING (true);

CREATE POLICY "Allow public delete on live_seat_matrix" 
ON public.live_seat_matrix FOR DELETE USING (true);


-- ==========================================
-- 7. FORUM POSTS TABLE
-- ==========================================

-- Create 'forum_posts' table
CREATE TABLE IF NOT EXISTS public.forum_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    category TEXT NOT NULL,
    student_name TEXT NOT NULL,
    student_roll TEXT NOT NULL,
    upvotes INTEGER DEFAULT 0 NOT NULL,
    reports_count INTEGER DEFAULT 0 NOT NULL,
    is_hidden BOOLEAN DEFAULT false NOT NULL,
    is_premium BOOLEAN DEFAULT false NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.forum_posts ENABLE ROW LEVEL SECURITY;

-- Policies for forum_posts
CREATE POLICY "Allow public select on forum_posts" ON public.forum_posts FOR SELECT USING (true);
CREATE POLICY "Allow public insert on forum_posts" ON public.forum_posts FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on forum_posts" ON public.forum_posts FOR UPDATE USING (true);
CREATE POLICY "Allow public delete on forum_posts" ON public.forum_posts FOR DELETE USING (true);


-- ==========================================
-- 8. FORUM COMMENTS TABLE
-- ==========================================

-- Create 'forum_comments' table
CREATE TABLE IF NOT EXISTS public.forum_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT REFERENCES public.forum_posts(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    student_name TEXT NOT NULL,
    student_roll TEXT NOT NULL,
    reports_count INTEGER DEFAULT 0 NOT NULL,
    is_hidden BOOLEAN DEFAULT false NOT NULL,
    is_premium BOOLEAN DEFAULT false NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.forum_comments ENABLE ROW LEVEL SECURITY;

-- Policies for forum_comments
CREATE POLICY "Allow public select on forum_comments" ON public.forum_comments FOR SELECT USING (true);
CREATE POLICY "Allow public insert on forum_comments" ON public.forum_comments FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on forum_comments" ON public.forum_comments FOR UPDATE USING (true);
CREATE POLICY "Allow public delete on forum_comments" ON public.forum_comments FOR DELETE USING (true);


-- ==========================================
-- 9. FORUM VOTES TABLE
-- ==========================================

-- Create 'forum_votes' table
CREATE TABLE IF NOT EXISTS public.forum_votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT REFERENCES public.forum_posts(id) ON DELETE CASCADE,
    student_roll TEXT NOT NULL,
    vote_type TEXT DEFAULT 'upvote' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(post_id, student_roll)
);

-- Enable RLS
ALTER TABLE public.forum_votes ENABLE ROW LEVEL SECURITY;

-- Policies for forum_votes
CREATE POLICY "Allow public select on forum_votes" ON public.forum_votes FOR SELECT USING (true);
CREATE POLICY "Allow public insert on forum_votes" ON public.forum_votes FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public delete on forum_votes" ON public.forum_votes FOR DELETE USING (true);


-- ==========================================
-- 10. FORUM REPORTS TABLE
-- ==========================================

-- Create 'forum_reports' table
CREATE TABLE IF NOT EXISTS public.forum_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT REFERENCES public.forum_posts(id) ON DELETE CASCADE,
    comment_id BIGINT REFERENCES public.forum_comments(id) ON DELETE CASCADE,
    student_roll TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_post_report UNIQUE(post_id, student_roll),
    CONSTRAINT unique_comment_report UNIQUE(comment_id, student_roll)
);

-- Enable RLS
ALTER TABLE public.forum_reports ENABLE ROW LEVEL SECURITY;

-- Policies for forum_reports
CREATE POLICY "Allow public select on forum_reports" ON public.forum_reports FOR SELECT USING (true);
CREATE POLICY "Allow public insert on forum_reports" ON public.forum_reports FOR INSERT WITH CHECK (true);


-- ==========================================
-- 11. STUDENT LOGINS STREAM TABLE
-- ==========================================

-- Create 'student_logins' table
CREATE TABLE IF NOT EXISTS public.student_logins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roll TEXT NOT NULL,
    name TEXT NOT NULL,
    rank INTEGER NOT NULL,
    category TEXT NOT NULL,
    is_premium BOOLEAN DEFAULT false,
    is_demo BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.student_logins ENABLE ROW LEVEL SECURITY;

-- Policies for student_logins
CREATE POLICY "Allow public select on student_logins" ON public.student_logins FOR SELECT USING (true);
CREATE POLICY "Allow public insert on student_logins" ON public.student_logins FOR INSERT WITH CHECK (true);
